web/js/showImageOnMenu.js
The preview would show up regardless of being enabled (as the `b_preview` handler did not check `enabled`). This fixes that.
I've also taken the liberty to improve the way the image is embedded into the menu. Instead of adding/removing from the DOM, `display: none` is preferred instead. And I've used flexbox's `order` to put the preview at the bottom instead of the `absolute` method you used before, enabling other extensions to also place items at the bottom (as they would otherwise have to fight this extension for the bottom padding)
=> Improve image preview script

web/js/workflows.js
Currently the Load workflow menu has its menu shows at random order. 
This PR add sorting so the workflows display in alphabetical order.
=> sort workflow items in the load workflow menu

py/math_expression.py
ComfyUI does not send the argument at all when using the API, and is making MathExpression node to crash
=> making extra_pnginfo argument optional.

web/js/betterCombos.js
Proposed fix for https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/177
This happens because during refresh it checks if the loader is still in the list of values (https://github.com/comfyanonymous/ComfyUI/blob/7f4725f6b3f72dd8bdb60dae5dd2c3e943263bcf/web/scripts/app.js#L2208-L2209), but this always fails due to it comparing objects (whereas the default loaders compare a string value with list of strings).
The issue only occurs when `widget.options.values[0]` is a file in the root folder. When it is in a subfolder, 
```
if (v?.submenu) {
// Dont allow selection of submenus
return;
}
```
prevents the value from being set to the default.
=> Fix refresh resetting loader values to default

web/js/autocompleter.js, web/js/common/autocomplete.js
Fixes #165.
Having the `replace _ with space` option enabled will cause embeddings/loras with underscores to be replaced by spaces, which can cause this warning: `warning, embedding:test does not exist, ignoring`, where the correct embedding name changes from `embedding:test_name` to `embedding:test name`.
Fixed by excluding embeddings and loras from using the replacer. I imagine the replacer is mostly meant for tags, so it seems fine for this to always to be disabled for embeddings and loras.
=> Fix autocomplete replacing embedding and lora underscores with spaces

web/js/betterCombos.js
Fixes https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/197.
Problem is that `(` and `)` are not encoded when using `encodeURIComponent`. Have replaced it to use the encoding implementation from
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#encoding_for_rfc3986 instead which includes encoding the `!`, `'`, `(`, `)`, `*` characters.
Have tested this with the lora loader in chrome/firefox/edge with an image called `!'().jpeg` (no `*` because it cannot be used in windows filenames) and confirmed that it works.
=> Fix uri encoding for preview image

web/js/autocompleter.js
Looks like there are a couple of imports that attempt to go up one directory higher than they should.
Was running into a stubborn issue with this file where it would not be loaded by ComfyUI when accessing Comfy hosted in a subdirectory using a reverse proxy (e.g., [http://example.com/comfy/]()). When hosted at the root, the extra `../` is silently ignored and all appears well, but when running Comfy in a subdirectory, it ends up going outside of the subdirectory and causes these imports to fail, causing the autocompleter extension to fail.
Should solve #179, as I was seeing the same issue.
=> Fix relative import paths in autocompleter.js

web/js/common/autocomplete.js
Yes, execCommand is deprecated, but it's what's available to us at the moment. A fallback is also included in the event that support for execCommand is dropped or not present.
=> Add undo support to autocomplete

web/js/imageFeed.js
Should default to flex for visibility, since the menu and list children assume that they're flex items.
=> Fix display type for image feed when toggled

web/js/imageFeed.js
(Thank you for your work!)
**Problem**
Some nodes can generate the same image for consecutive generations, which clutters the image feed with duplicate images:
There are two categories of duplicate images to consider, here:
1. Two images point to the same file on server.
2. Two images look the same but are stored differently on server, potentially with unique metadata.
**Solution**
1. Memoize the image `src` metadata (filename/type/subfolder) and hash (sans metadata).
2. Prevent addition to the feed if we've seen either the metadata or the hash before.
**Performance**
_(tested on Ryzen 9 3950X w/ 64 MB RAM, running on local instance of comfy)_
~69% of the performance hit is due the additional drawing on an invisible canvas, in order to get image data without the metadata. For workflows …
=> image feed deduplication

py/string_function.py
I made the text inputs optional because I've been toggling them on/off a lot and made some other improvements while I'm in here.
- Made texts optional when converted to inputs. There are no edge-cases where this breaks.
- Removed workarounds for unconnected inputs, since Comfy now simply omits them in the method call.
- Switched `tidy_tags` conversion to regex to also properly tidy cases of 3+ spaces and 4+ commas
Please let me know if you have any thoughts or concerns about these changes.
=> StringFunction Improvements

README.md, py/system_notification.py, web/js/systemNotification.js
This node is a direct mirror of PlaySound, except it sends a system notification via the browser instead of playing audio.
Simple Workflow Example:
On trigger, a system notification will pop up:
Tested on Firefox and Chrome on MacOS.
=> Adds node for sending system notifications.

web/js/common/modelInfoDialog.js
Fix the broken image issue in Model Info panel.
=> fix: fetch the image type only if there's a possibility of a video type.

web/js/workflowImage.js
Save and restore the transformation matrix. This ensures that visual properties and transformations are maintained across operations that require resizing or modifying the canvas. The update resolves issues related to unintended scaling and transformation resets when the canvas dimensions are programmatically changed.
Explanation: This line changes the canvas's property:
```
app.canvas.canvas.width = app.canvas.canvas.width;
```
This might at first lance seem like it should have no effect, but it actually does due to how the canvas element handles changes to its width and height properties.
=> Save and restore the transformation matrix during exporting

web/js/common/autocomplete.js
Autocomplete pops up when pressing shift, control, home, end, etc.  I really wanted the feature, though - now it shows only when the key value is <= 1 (e.g. any character entry `d`, `=`, `9`), or the key was backspace/delete.
=> Fix autocomplete opening on unrelated keypresses

web/js/snapToGrid.js
Hi,
This PR adds a quality-of-life improvement for keeping nodes neatly aligned in a workflow.
Consider the current behavior when organizing a node (snap to grid turned on):
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/83140/b7e40ebc-3796-45b2-8e4c-11897d57a5a0
Except for the faint preview box, indicating where the node will snap to, it's difficult to align a node with others (especially if they are far apart in the workflow).
1. Display orthogonal guide lines that extend across the canvas. This helps align a node with other nodes.
2. Customize the preview box for improved visibility.
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/83140/862d9482-040a-472d-a26e-9c7144e500c6
=> show guide lines/boxes for nodes

py/better_combos.py
Fixes #259.
The value of `lora_name` and `ckpt_name` is a dict containing the location of both the model and preview image, e.g:
`{"content": "path/to/model", "image": "path/to/image"}`
so the default validation is checking that not only the model exists, but the image exists as well. A change in the path of the image (e.g. going from `jpg`->`png` or having it deleted) should not affect the validation, but currently does.
Tested this fix by:
1. Selecting a model in the loader
2. Renaming the image file
3. Confirming running the prompt no longer raises a validation error
=> Improve image loader validation to only consider model file

web/js/common/lightbox.css, web/js/common/spinner.css
When scrolling through images in the Image Feed, there is a brief jitter as images are loaded.
The loading spinner is an inline sibling element of the image element.
Use absolute positioning on the spinner root element, relative to the containing pysssss-lightbox-link element.  Use flex to centre the lightbox contents.
=> Fix lightbox loading position

web/js/contextMenuHook.js
Fix for the issue where the ContextMenu object created by the overridden ContextMenu constructor cannot be accessed
=> fix: The return of ctx is missing in the overriding of LiteGraph.ContextMenu

web/js/snapToGrid.js, web/js/snapToGridGuide.js
Splits the snapToGridGuide extension from snapToGrid extension.
Always snap to grid setting was implemented in core in https://github.com/Comfy-Org/ComfyUI_frontend/pull/1177 and the `pysssss.SnapToGrid` extension id is disabled.
This PR splits out the snapToGrid guideline feature from the disabled `pysssss.SnapToGrid` extension so users can still use this feature. The guideline is probably too much for all users, so leaving it in the extension for now.
Ref issue: https://github.com/Comfy-Org/ComfyUI_frontend/issues/1181
=> Split snapToGrid extension

web/js/presetText.js
Fixes:
- #331
- #336 
Because of Comfy-Org/ComfyUI_frontend#667 (Comfy-Org/litegraph.js#98), it's necessary to subclass nodes to inherit `LGraphNode` properties.
=> Fix PresetText node

web/js/snapToGridGuide.js
Related issue: https://github.com/Comfy-Org/ComfyUI_frontend/issues/1181#issuecomment-2433369678
Follow-up of https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/370
Previously `app.shiftDown` directly determines whether snapToGrid is enabled or not, but now it also depends on whether always snap to grid setting is enabled. This PR fixes the enable condition.
=> Fix snap guide enable condition

web/js/workflowImage.js
When saving the workflow as a PNG, a white area appears (bug). #359 
The dependency library has adjusted the size of background image on high DPI devices, as shown in the image below.
One of the solution is to adjust the size of canvas when saving images(modify the function `updateView`).
(This issue can also be fixed by temporarily setting window.devicePixelRatio to 1, but it may not seem like a good idea.)
=> Fix: fix transparent background when saving the workflow

py/workflows.py
pysssss.json can use relative path, such as:
{
"name": "CustomScripts",
"logging": false,
"workflows": {
"directory": "../A-workflows"
}
}
=> Enables the configuration to use relative paths

web/js/workflowImage.js
This pull request is to fix the offset problem caused by #375. 
#375 fixed the problem of exporting images on high DPI devices by multiplying the image `width`, `height` and `transform` by the `devicePixelRatio`. But it also multiplied the `offset` by the `devicePixelRatio`, which caused some workflows with large offsets to not be correctly displayed in the center of the exported image.
=> fix: the offset should not be multiplied by the scale

web/js/workflows.js
refreshComboInNodes is now an invoked extension hook, so instead of hijacking app.refreshComboInNodes, you can just provide the method and reduce incompatibility issues.
(Discovered because I was doing the same thing in cg-controller, and our two hijacks weren't playing nicely!)
=> provide refreshComboInNodes

web/js/autocompleter.js, web/js/common/autocomplete.js
1. Search values with underscore by using blank space instead underscore
2. Show values when type in dynamic prompt
=> Improve usability of Autocomplete

py/constrain_image.py
Current
When ConstrainImage is provided with an image that is smaller than max width & height, it will always scale the image up.
New behaviour
If an image already falls within the constraint min/max bounds, it is not scaled.
=> Fix ConstrainImage increases size

web/js/betterCombos.js
This PR resolves #413 by updating the lora/model combo preview to work with https://github.com/Comfy-Org/litegraph.js/pull/414.
Changes include:
- Use constant for width/height of preview image
- Attach image preview to body instead of the context menu directly, as the context menu no longer shows overflow
- Add mouseenter, mouseleave, and click handlers to manually calculate and update the position/visibility of the preview image
=> Update lora/model combo preview

web/js/imageFeed.js
This PR adds a new checkbox setting under Image Feed: "🐍 Image Feed Display 'SaveImage' Only" to allow users to only display images from the 'Save Image' node with a simple toggle. 
When using additional pre- and post-processing elements in advanced workflows, it's helpful to visualize specific components through the workflow’s PreviewImage nodes. However, many of these elements are only intended for internal visibility and can clutter the Image Feed with unnecessary content. This option improves clarity and user experience by displaying only intentional outputs.
- Adds a boolean setting saved in localStorage
- Filters images in the Image Feed based on node type (If toggled on 'SaveImage' Nodes only)
- Defaults to showing all images
=> Image Feed Setting added to only display 'Save Image' node output(s) in Image Feed
